CREATE VIEW VALID_PRESCRIPTION_VW AS
	SELECT PRESCRIPTION.RX_NUMBER, CONSUMER.FIRST_NAME, CONSUMER.LAST_NAME,
		DRUG.NAME, DRUG.DESCRIPTION
		PRESCRIPTION.DATE_CREATED, PRESCRIPTION.EXPIRATION_DATE, PRESCRIPTION.QUANTITY, 
		PRESCRIPTION.NUMBER_OF_REFILLS, PRESCRIPTION.ADDITIONAL_INFORMATION,
		DOCTOR.FIRST_NAME, DOCTOR.LAST_NAME
	FROM PRESCRIPTION, CONSUMER, DRUG, DOCTOR
	WHERE (EXPIRATION_DATE < "2022-05-02")
	AND (PRESCRIPTION.CONSUMER_ID = CONSUMER.ID)
	AND (PRESCRIPTION.DRUG_ID = DRUG.ID)
	AND (PRESCRIPTION.DOCTOR_ID = DOCTOR.ID);


CREATE VIEW VALID_PRESCRIPTION_VW AS
	SELECT PRESCRIPTION.RX_NUMBER, CONSUMER.FIRST_NAME, CONSUMER.LAST_NAME,
		DRUG.NAME, DRUG.DESCRIPTION
		PRESCRIPTION.DATE_CREATED, PRESCRIPTION.EXPIRATION_DATE, PRESCRIPTION.QUANTITY, 
		PRESCRIPTION.NUMBER_OF_REFILLS, PRESCRIPTION.ADDITIONAL_INFORMATION,
		DOCTOR.FIRST_NAME, DOCTOR.LAST_NAME
	FROM PRESCRIPTION
	JOIN CONSUMER ON PRESCRIPTION.CONSUMER_ID = CONSUMER.ID
	JOIN DRUG ON PRESCRIPTION.DRUG_ID = DRUG.ID
	JOIN DOCTOR ON PRESCRIPTION.DOCTOR_ID = DOCTOR.ID
	WHERE PRESCRIPTION.EXPIRATION_DATE < "2022-05-02";


CREATE VIEW NUM_PRESCRIPTIONS_PER_CONSUMER_VW AS
	SELECT PRESCRIPTION.RX_NUMBER, DRUG.NAME, DRUG.DESCRIPTION, PRESCRIPTION.DATE_CREATED,
		PRESCRIPTION.EXPIRATION_DATE, PRESCRIPTION.QUANTITY, PRESCRIPTION.NUMBER_OF_REFILLS,
		PRESCRIPTION.ADDITION_INFORMATION, DOCTOR.FIRST_NAME, DOCTOR.LAST_NAME
	FROM PRESCRIPTION
	JOIN CONSUMER ON PRESCRIPTION.CONSUMER_ID = CONSUMER.ID
		AND CONSUMER.FIRST_NAME = "Sally"
		AND CONSUMER.LAST_NAME = "Brown"
	JOIN DRUG ON PRESCRIPTION.DRUG_ID = DRUG.ID
	JOIN DOCTOR ON PRESCRIPTION.DOCTOR_ID = DOCTOR.ID;

# View - number of patients per doctor
CREATE VIEW DOCTOR_PATIENT_COUNT AS
	SELECT DISTINCT d.FIRST_NAME,d.LAST_NAME, COUNT(*) AS Total
	FROM pharmacy2.Doctor as d
	JOIN pharmacy2.Consumer as c
	ON d.ID = c.DOCTOR_ID
	GROUP BY d.ID 
	ORDER BY COUNT(*) DESC;

# Finding the total quantity of drug available on inventory based on manfacturing id
CREATE VIEW DRUG_QUANTITY_AVAILABLE AS
	SELECT SUM(QUANTITY) FROM Inventory WHERE MANUFACTURER_ID=4;

# Finding the total quantity of drug available on inventory based on drug id
CREATE VIEW DRUG_QUANTITY_AVAILABLE AS
	SELECT SUM(QUANTITY) FROM Inventory WHERE  DRUG_ID=4;

# Finding the total quantity of drug available on inventory based on location.
CREATE VIEW DRUG_QUANTITY_AVAILABLE AS
	SELECT QUANTITY FROM Inventory WHERE LOCATION="Aisle 10, Cabinet 3";

# Finding the information of drug available on inventory based on quantity. This is if quantity is less than 100.
CREATE VIEW DRUG_INVENTORY_INFORMATION AS
	SELECT * FROM Inventory WHERE QUANTITY<100;
